// Code generated by protoc-gen-go.
// source: Message.proto
// DO NOT EDIT!

/*
Package vcron is a generated protocol buffer package.

It is generated from these files:
	Message.proto

It has these top-level messages:
	Message
*/
package vcron

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Message struct {
	Type             *string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Command          *string `protobuf:"bytes,3,opt,name=command" json:"command,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Message) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Message) GetCommand() string {
	if m != nil && m.Command != nil {
		return *m.Command
	}
	return ""
}

func init() {
	proto.RegisterType((*Message)(nil), "vcron.Message")
}

var fileDescriptor0 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xf5, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x4b, 0x2e, 0xca, 0xcf,
	0x53, 0x32, 0xe3, 0x62, 0x87, 0x8a, 0x0b, 0xf1, 0x70, 0xb1, 0x94, 0x54, 0x16, 0xa4, 0x4a, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x82, 0x78, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x1e, 0x3f, 0x17,
	0x7b, 0x72, 0x7e, 0x6e, 0x6e, 0x62, 0x5e, 0x8a, 0x04, 0x33, 0x48, 0x00, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x98, 0x4d, 0x1e, 0xa7, 0x4e, 0x00, 0x00, 0x00,
}
